<?xml version="1.0"?>
<package format="3">
  <name>my_arm_driver</name>
  <version>0.0.1</version>
  <description>Driver per al braç robot d'Amazon usant comunicació sèrie</description>
  <maintainer email="manel.puig@ub.edu">Manel Puig</maintainer>
  <license>MIT</license>

  <depend>rclpy</depend>
  <depend>std_msgs</depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep8</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
