sequence_name: ur5e_handshake_planned

common:
  execute: false
  group_name: arm
  ik_link: tool
  target_frame: base_link
  planning_frame: base_link
  ik_timeout_sec: 1.0
  print_joints: true

  max_velocity: 0.10
  max_acceleration: 0.10
  avoid_collisions: true

  max_step: 0.005
  fraction_threshold: 1.0
  jump_threshold: 0.0

steps:
  - name: home_start
    motion_type: movej
    target_xyz: [0, -400, 500]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: false
    seed_joints: [-60, -60, -100, 170, -90, 0]
    duration: 4.0
    sleep_after: 1.0

  - name: approach_handshake
    motion_type: movel
    target_xyz: [-250, -350, 300]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: true
    duration: 4.0
    sleep_after: 1.0

  - name: handshake
    motion_type: movel
    target_xyz: [-250, -350, 200]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: true
    duration: 1.0
    sleep_after: 1.0

  - name: retreat_handshake
    motion_type: movel
    target_xyz: [-250, -350, 300]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: true
    duration: 1.0
    sleep_after: 1.0

  - name: home_end
    motion_type: movej
    target_xyz: [0, -400, 500]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: false
    seed_joints: [-60, -60, -100, 170, -90, 0]
    duration: 4.0
    sleep_after: 1.0