common:
  execute: true

  group_name: arm
  ik_link: tool

  target_frame: base_link
  planning_frame: base_link

  ik_timeout_sec: 1.0
  print_joints: true

steps:

  - name: home_start
    target_xyz: [0, -400, 500]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: false
    seed_joints: [-60, -60, -100, 170, -90, 0]
    duration: 4.0
    sleep_after: 1.0

  - name: approach_handshake
    target_xyz: [-250, -350, 300]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: true
    duration: 4.0
    sleep_after: 1.0

  - name: handshake
    target_xyz: [-250, -350, 200]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: true
    duration: 1.0
    sleep_after: 1.0

  - name: retreat_handshake
    target_xyz: [-250, -350, 300]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: true
    duration: 1.0 
    sleep_after: 1.0

  - name: home_end
    target_xyz: [0, -400, 500]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: false
    seed_joints: [-60, -60, -100, 170, -90, 0]
    duration: 4.0
    sleep_after: 1.0