common:
  execute: true
  group_name: arm
  ik_link: tool
  target_frame: base_link
  planning_frame: base_link
  ik_timeout_sec: 1.0
  print_joints: true

steps:
  - name: home_start
    target_xyz: [0, -400, 500]
    target_rpy: [0.0, 0.0, 0.0]
    seed_from_joint_states: false
    seed_joints: [-60, -60, -100, -90, -90, 0]
    duration: 4.0
    sleep_after: 1.0

  - name: approach_give5
    target_xyz: [-300, -300, 500]
    target_rpy: [0.0, 0.0, 0.0]
    seed_from_joint_states: true
    duration: 4.0
    sleep_after: 1.0

  - name: give5
    target_xyz: [-300, -400, 500]
    target_rpy: [0.0, 0.0, 0.0]
    seed_from_joint_states: true
    duration: 1.0
    sleep_after: 1.0

  - name: retreat_give5
    target_xyz: [-300, -300, 500]
    target_rpy: [0.0, 0.0, 0.0]
    seed_from_joint_states: true
    duration: 1.0 
    sleep_after: 1.0

  - name: home_end
    target_xyz: [0, -400, 500]
    target_rpy: [0.0, 0.0, 0.0]
    seed_from_joint_states: false
    seed_joints: [-60, -60, -100, -90, -90, 0]
    duration: 4.0
    sleep_after: 1.0