common:
  execute: true
  group_name: ur_manipulator
  ik_link: tool0

  target_frame: table
  planning_frame: base_link

  max_velocity: 0.1
  max_acceleration: 0.1
  ik_timeout_sec: 1.0
  print_joints: true

steps:
  - name: home_start
    target_xyz: [0, -400, 500]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: false
    seed_joints: [-60, -60, -100, 170, -60, 0]
    duration: 4.0
    sleep_after: 1.0

  - name: approach_handshake
    target_xyz: [-300, -300, 500]
    target_rpy: [0.0, 0.0, 90.0]
    seed_from_joint_states: true
    duration: 4.0
    sleep_after: 1.0

  - name: handshake
    target_xyz: [-300, -400, 500]
    target_rpy: [0.0, 0.0, 90.0]
    seed_from_joint_states: true
    duration: 4.0
    sleep_after: 1.0

  - name: retreat_handshake
    target_xyz: [-300, -300, 500]
    target_rpy: [0.0, 0.0, 90.0]
    seed_from_joint_states: true
    duration: 4.0 
    sleep_after: 1.0

  - name: home_end
    target_xyz: [0, -400, 500]
    target_rpy: [90.0, 0.0, 0.0]
    seed_from_joint_states: false
    seed_joints: [-60, -60, -100, 170, -60, 0]
    duration: 4.0
    sleep_after: 1.0